In [2]:
import numpy as np

def perceptron(X, y, learning_rate=0.1, n_iterations=10):
    n_samples, n_features = X.shape
    weights = np.zeros(n_features)
    bias = 0

    for _ in range(n_iterations):
        for idx, x_i in enumerate(X):
            linear_output = np.dot(x_i, weights) + bias
            y_predicted = 1 if linear_output >= 0 else 0
            update = learning_rate * (y[idx] - y_predicted)
            weights += update * x_i
            bias += update
    return weights, bias

def predict(X, weights, bias):
    linear_output = np.dot(X, weights) + bias
    return np.where(linear_output >= 0, 1, 0)

if __name__ == "__main__":
    # Create synthetic data
    X = np.array([
        [25, 200, 3, 5000],
        [30, 400, 5, 6000],
        [35, 150, 2, 3000],
        [40, 300, 4, 7000],
        [45, 100, 1, 2000],
    ], dtype=np.float64)
    y = np.array([1, 1, 0, 1, 0], dtype=np.float64)  # Example target labels

    print("First few rows of X:", X[:5])
    print("First few entries of y:", y[:5])

    # Train the perceptron model
    weights, bias = perceptron(X, y, learning_rate=0.1, n_iterations=10)
    predictions = predict(X, weights, bias)

    print("Weights:", weights)
    print("Bias:", bias)
    print("Predictions:", predictions)


First few rows of X: [[2.5e+01 2.0e+02 3.0e+00 5.0e+03]
 [3.0e+01 4.0e+02 5.0e+00 6.0e+03]
 [3.5e+01 1.5e+02 2.0e+00 3.0e+03]
 [4.0e+01 3.0e+02 4.0e+00 7.0e+03]
 [4.5e+01 1.0e+02 1.0e+00 2.0e+03]]
First few entries of y: [1. 1. 0. 1. 0.]
Weights: [-5.45e+01 -5.00e+01 -1.00e-01 -1.00e+02]
Bias: -1.0999999999999999
Predictions: [0 0 0 0 0]
